<a href="https://colab.research.google.com/github/dngtundt/THDL_Buoi1/blob/main/THDL_Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ĐẶNG ANH TUẤN - 2001230850

NUMPY & PANDAS

3.1.
Tạo array 1 chiều

In [252]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print('Python list:', my_list)

# chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print('Numpy array:', my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


3.2. Array 2-chiều

In [253]:
c = np.array([(1, 2, 3),
              (4, 5, 6)])

print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


3.3. Array 3-chiều

In [254]:
d = np.array([
              [[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10, 11, 12]]
            ])

print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


3.4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [255]:
e = np.zeros((2, 2))
f = np.ones((3, 3))

print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.5.1. Reshape thay đổi kích thước ma trận

In [256]:
e = np.array([[1., 2., 3.], [4., 5., 6.]])
print(e)
print(e.shape)

f = e.reshape(3, 2)
print(f)

g = np.array([[[1., 2., 3.], [4., 5., 6.]],
              [[7., 8., 9.], [10., 11., 12.]]
             ])
print(g)
print(g.shape)

h = g.reshape(3, 4)
print('reshape (3, 4)\n', h)

j = g.reshape(3, 2, 2)
print('reshape (3, 2, 2)\n', j)

k = g.reshape(2, 3, 2)
print('reshape (2, 3, 2)\n', k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


BÀI TẬP NUMPY_PANDAS

In [257]:
print("="*40)
print("BÀI 1: Hàm np.all() - Kiểm tra TẤT CẢ khác 0")
print("="*40)
# Tạo mảng 3x3 ngẫu nhiên từ 0 đến 20 (chứa cả 20)
arr1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 1:\n", arr1)
# Kiểm tra tất cả khác 0 (nếu có 1 số 0 sẽ trả về False)
is_all_nonzero = np.all(arr1 != 0)
print("Tất cả phần tử đều khác 0?:", is_all_nonzero)

BÀI 1: Hàm np.all() - Kiểm tra TẤT CẢ khác 0
Mảng 1:
 [[10 13 20]
 [16 20  3]
 [ 0 13  5]]
Tất cả phần tử đều khác 0?: False


In [258]:
print("BÀI 2: Hàm np.any() - Kiểm tra TỒN TẠI phần tử khác 0")
print("="*40)
arr2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 2:\n", arr2)
# Kiểm tra có ít nhất 1 phần tử khác 0 (chỉ cần 1 số khác 0 sẽ trả về True)
is_any_nonzero = np.any(arr2 != 0)
print("Có tồn tại phần tử khác 0?:", is_any_nonzero)

BÀI 2: Hàm np.any() - Kiểm tra TỒN TẠI phần tử khác 0
Mảng 2:
 [[11  0 16]
 [ 3  1  2]
 [16 14 20]]
Có tồn tại phần tử khác 0?: True


In [259]:
print("\n" + "="*40)
print("BÀI 3: So sánh 2 mảng bằng greater, less...")
print("="*40)
# --- Mảng 1 chiều ---
a1 = np.array([1, 5, 10])
b1 = np.array([5, 5, 5])
print("Mảng 1D a:", a1)
print("Mảng 1D b:", b1)
print("a > b  (greater)      :", np.greater(a1, b1))
print("a >= b (greater_equal):", np.greater_equal(a1, b1))
print("a < b  (less)         :", np.less(a1, b1))
print("a <= b (less_equal)   :", np.less_equal(a1, b1))
# --- Mảng 2 chiều ---
a2 = np.array([[1, 5], [10, 2]])
b2 = np.array([[5, 5], [5, 5]])
print("\nMảng 2D a:\n", a2)
print("Mảng 2D b:\n", b2)
print("a > b (greater):\n", np.greater(a2, b2))


BÀI 3: So sánh 2 mảng bằng greater, less...
Mảng 1D a: [ 1  5 10]
Mảng 1D b: [5 5 5]
a > b  (greater)      : [False False  True]
a >= b (greater_equal): [False  True  True]
a < b  (less)         : [ True False False]
a <= b (less_equal)   : [ True  True False]

Mảng 2D a:
 [[ 1  5]
 [10  2]]
Mảng 2D b:
 [[5 5]
 [5 5]]
a > b (greater):
 [[False False]
 [ True False]]


In [260]:
print("BÀI 4: Tạo mảng 10 số 1, 10 số 0, 10 số 5")
print("="*40)
# np.ones tạo số 1, np.zeros tạo số 0, np.full tạo mảng với giá trị chỉ định
arr4 = np.concatenate((np.ones(10), np.zeros(10), np.full(10, 5)))
print("Kết quả:\n", arr4)

BÀI 4: Tạo mảng 10 số 1, 10 số 0, 10 số 5
Kết quả:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [261]:

print("\n" + "="*40)
print("BÀI 5: Tạo mảng số nguyên chẵn từ [30, 70]")
print("="*40)
# Dùng arange(start, stop, step). Stop phải là 72 để lấy được cả số 70.
arr5 = np.arange(30, 72, 2)
print("Kết quả:\n", arr5)


BÀI 5: Tạo mảng số nguyên chẵn từ [30, 70]
Kết quả:
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [262]:
print("BÀI 6: Tạo ma trận đơn vị 3x3")
print("="*40)
# Hàm np.identity(n) tạo ma trận vuông cấp n với đường chéo chính là 1, còn lại là 0
arr6 = np.identity(3)
print("Ma trận đơn vị 3x3:\n", arr6)

BÀI 6: Tạo ma trận đơn vị 3x3
Ma trận đơn vị 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [263]:
import numpy as np
arr = np.linspace(15, 55, 10)
print("Mảng:", arr)
print("Các phần tử giữa:", arr[1:-1])

Mảng: [15.         19.44444444 23.88888889 28.33333333 32.77777778 37.22222222
 41.66666667 46.11111111 50.55555556 55.        ]
Các phần tử giữa: [19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]


In [264]:
# Bài 7: Tạo mảng 10 phần tử [15, 55], in các giá trị trừ phần tử đầu và cuối
import numpy as np
arr7 = np.linspace(15, 55, 10)
print("Mảng:", arr7)
print("Các giá trị trừ đầu và cuối:", arr7[1:-1])

Mảng: [15.         19.44444444 23.88888889 28.33333333 32.77777778 37.22222222
 41.66666667 46.11111111 50.55555556 55.        ]
Các giá trị trừ đầu và cuối: [19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]


In [265]:
# Bài 8: Tạo mảng 20 phần tử [0, 20] và đổi dấu những số trong khoảng [9, 15]
arr8 = np.random.randint(0, 21, 20)
print("Mảng gốc:", arr8)
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1
print("Mảng sau đổi dấu:", arr8)

Mảng gốc: [ 3  1 13  8  1  3  8 20  2  3  3 18 10  4 16 17  3 11 13 17]
Mảng sau đổi dấu: [  3   1 -13   8   1   3   8  20   2   3   3  18 -10   4  16  17   3 -11
 -13  17]


In [266]:
# Bài 9: Tạo ma trận 3 x 4 với các phần tử trong khoảng [10, 21]
arr9 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", arr9)

Ma trận 3x4:
 [[14 19 21 11]
 [12 19 12 21]
 [13 10 16 13]]


In [267]:
# Bài 10: Ma trận 10 x 10, biên bằng 1, trong bằng 0
arr10 = np.zeros((10, 10))
arr10[0, :] = 1; arr10[-1, :] = 1
arr10[:, 0] = 1; arr10[:, -1] = 1
print("Ma trận biên 1:\n", arr10)

Ma trận biên 1:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [268]:
# Bài 11: Ma trận 5 x 5, đường chéo chính là 1, 2, 3, 4, 5
arr11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", arr11)

Ma trận đường chéo:
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [269]:
# Bài 12: Mảng 3x3x3, tính tổng theo dòng và cột
arr12 = np.random.randint(1, 10, (3, 3, 3))
print("Tổng theo dòng (axis=1):", np.sum(arr12, axis=1))
print("Tổng theo cột (axis=0):", np.sum(arr12, axis=0))

Tổng theo dòng (axis=1): [[22 13  9]
 [20 20 16]
 [21 13 23]]
Tổng theo cột (axis=0): [[19 19 18]
 [21 19 12]
 [23  8 18]]


In [270]:
# Bài 13: Inner product (np.dot) 2 vector 10 phần tử
v1 = np.random.rand(10)
v2 = np.random.rand(10)
print("Inner product:", np.dot(v1, v2))

Inner product: 2.1572924301424274


In [271]:
# Bài 14: Cộng vector y vào từng dòng ma trận A (Broadcasting)
A = np.random.randint(1, 10, (4, 3))
y = np.random.randint(1, 5, 3)
result14 = A + y
print("Ma trận A + y:\n", result14)

Ma trận A + y:
 [[12  2  6]
 [11  2  9]
 [ 8  8 11]
 [ 7  4  7]]


In [272]:
# Bài 15: Pandas cộng, trừ, nhân, chia 2 Series
import pandas as pd
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64


In [273]:
# Bài 16: Pandas chuyển đổi cột đầu tiên thành Series
df16 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
series16 = df16.iloc[:, 0] # Lưu ý: ix đã bị deprecated, nên dùng iloc
print("Series từ cột 1:\n", series16)

Series từ cột 1:
 0    1
1    2
Name: A, dtype: int64


In [274]:
# Bài 17: Sắp xếp DataFrame 4x3 theo cột
df17 = pd.DataFrame(np.random.rand(4, 3), columns=['X', 'Y', 'Z'])
print("Đã sắp xếp theo cột X:\n", df17.sort_values(by='X'))

Đã sắp xếp theo cột X:
           X         Y         Z
2  0.389356  0.985989  0.294250
1  0.401309  0.038504  0.005904
3  0.407252  0.758471  0.771512
0  0.734661  0.999024  0.846481


In [275]:
# Bài 18: Thay đổi index của Series
s18 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s18 = s18.reindex(['c', 'b', 'a'])
print("Series đã reindex:\n", s18)

Series đã reindex:
 c    30
b    20
a    10
dtype: int64


In [276]:
# Bài 19: Tìm phần tử trong sr1 không có trong sr2 dùng isin
import pandas as pd
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
res19 = sr1[~sr1.isin(sr2)]
print("Bài 19 - Các phần tử sr1 không có trong sr2:\n", res19)

Bài 19 - Các phần tử sr1 không có trong sr2:
 0    1
2    3
4    5
dtype: int64


In [277]:
# Bài 20: Hội (union) và Giao (intersect) của 2 Series
import numpy as np
x = pd.Series(np.random.randint(0, 20, 20))
y = pd.Series(np.random.randint(0, 20, 20))
print("Bài 20 - Hội (union1d):", np.union1d(x, y))
print("Bài 20 - Giao (intersect1d):", np.intersect1d(x, y))

Bài 20 - Hội (union1d): [ 0  2  3  4  5  6  7  8  9 10 11 12 15 16 17]
Bài 20 - Giao (intersect1d): [ 0  2  4  6  8  9 10 11 15 16]


In [278]:
# Bài 21: Thêm Series y vào Series x dọc và ngang
x21 = pd.Series(range(10))
y21 = pd.Series(list('pqrstuvwxy'))
print("Bài 21 - Chiều dọc (concat):\n", pd.concat([x21, y21]))
print("Bài 21 - Chiều ngang (concat DataFrame):\n", pd.concat([x21, y21], axis=1))

Bài 21 - Chiều dọc (concat):
 0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object
Bài 21 - Chiều ngang (concat DataFrame):
    0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [279]:
# Bài 22: Tạo DataFrame exam_data
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
print("Bài 22 - DataFrame:\n", df)

Bài 22 - DataFrame:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


In [280]:
# Bài 23, 24, 25, 26, 27: Truy vấn dữ liệu
print("Bài 23 - 3 dòng đầu:\n", df.head(3))
print("Bài 24 - Cột name & score:\n", df[['name', 'score']])
print("Bài 25 - Dòng có attempts > 2:\n", df[df['attempts'] > 2])
print("Bài 26 - Số dòng, số cột:", df.shape)
print("Bài 27 - Dòng có score là NaN:\n", df[df['score'].isnull()])

Bài 23 - 3 dòng đầu:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
Bài 24 - Cột name & score:
         name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0
Bài 25 - Dòng có attempts > 2:
       name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes
Bài 26 - Số dòng, số cột: (10, 4)
Bài 27 - Dòng có score là NaN:
     name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


In [281]:
# Bài 28, 29, 30: Truy vấn nâng cao và cập nhật
print("Bài 28 - Score trong (15, 20):\n", df[df['score'].between(15, 20)])
print("Bài 29 - Attempts > 2 và score trong (15, 20):\n", df[(df['attempts'] > 2) & (df['score'].between(15, 20))])

Bài 28 - Score trong (15, 20):
         name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
Bài 29 - Attempts > 2 và score trong (15, 20):
       name  score  attempts qualify
f  Michael   20.0         3     yes


In [282]:
# Bài 30: Thay đổi giá trị dòng 'd', cột 'score' thành 19
df.loc['d', 'score'] = 19
print("Bài 30 - DataFrame sau khi cập nhật dòng 'd':\n", df.loc[['d']])

Bài 30 - DataFrame sau khi cập nhật dòng 'd':
     name  score  attempts qualify
d  James   19.0         3      no


TENSOR

3.1 Tensor 1 chiều

In [283]:
import tensorflow as tf
# Mặc định là int32
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Tạo tensor scalar với các kiểu dữ liệu khác nhau
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


 3.2 Tensor 1-chiều (Vector)

In [284]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


3.3. Tensor 2-chiều (Ma trận)

In [285]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


3.4. Tensor n-chiều (Ví dụ Tensor 3-chiều)

In [286]:
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3.5. Thuộc tính của Tensor

In [287]:
print('\nShape:', rank_3_tensor.shape)
print('Type of tensor:', rank_3_tensor.dtype)


Shape: (3, 2, 5)
Type of tensor: <dtype: 'int32'>


3.6. Tạo tensor tự động gán giá trị 0

In [288]:
t_zero = tf.zeros(10)
print("\nZeros 1D:\n", t_zero)


Zeros 1D:
 tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [289]:
# 1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
t1 = tf.zeros([2, 3])
print("1. Tensor [2, 3] toàn số 0:\n", t1)

1. Tensor [2, 3] toàn số 0:
 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [290]:
# 2. Cho X = [[1, 2, 3], [4, 5, 6]], tạo tensor kích thước và dtype như X gán 0
X = [[1, 2, 3], [4, 5, 6]]
t2 = tf.zeros_like(X)
print("\n2. Tensor zeros_like X:\n", t2)


2. Tensor zeros_like X:
 tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [291]:
# 3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
t3 = tf.fill([3, 2], 5)
print("\n3. Tensor [3, 2] toàn số 5:\n", t3)


3. Tensor [3, 2] toàn số 5:
 tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [292]:
# 4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]
# Khoảng [5, 10] số chẵn 6, 8, 10.
# Giả sử 50 giá trị cách đều nhau:
t4 = tf.linspace(6.0, 10.0, 50)
print("\n4. Tensor 1D 50 phần tử từ 6 đến 10:\n", t4)


4. Tensor 1D 50 phần tử từ 6 đến 10:
 tf.Tensor(
[ 6.         6.0816326  6.163265   6.244898   6.3265305  6.408163
  6.4897957  6.5714283  6.6530614  6.734694   6.8163266  6.897959
  6.979592   7.0612245  7.142857   7.2244897  7.3061223  7.387755
  7.469388   7.5510206  7.632653   7.714286   7.7959185  7.877551
  7.9591837  8.040816   8.122449   8.204082   8.285714   8.367347
  8.448979   8.530612   8.612245   8.693877   8.77551    8.857142
  8.938776   9.020409   9.102041   9.183674   9.265306   9.346939
  9.428572   9.510204   9.591837   9.67347    9.755102   9.836735
  9.918367  10.       ], shape=(50,), dtype=float32)


In [293]:
# 5. Tạo một tensor 1-chiều có giá trị [10, 12, 14, …, 100]
t5 = tf.range(start=10, limit=101, delta=2)
print("\n5. Tensor cấp số cộng từ 10 đến 100:\n", t5)


5. Tensor cấp số cộng từ 10 đến 100:
 tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


In [294]:
# 6. Tensor [3, 2] ngẫu nhiên phân phối Normal (mean=0, stddev=2)
t6 = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)
print("\n6. Tensor Normal distribution:\n", t6)


6. Tensor Normal distribution:
 tf.Tensor(
[[ 4.4820576   0.05626165]
 [ 1.0685554   2.2010422 ]
 [-2.4374332   1.8694133 ]], shape=(3, 2), dtype=float32)


In [295]:
# 7. Tensor [3, 2] ngẫu nhiên phân phối Uniform trong phạm vi [0, 2]
t7 = tf.random.uniform(shape=[3, 2], minval=0, maxval=2)
print("\n7. Tensor Uniform distribution:\n", t7)


7. Tensor Uniform distribution:
 tf.Tensor(
[[0.69671893 1.3916998 ]
 [1.3600852  1.6433883 ]
 [0.2541299  1.8872366 ]], shape=(3, 2), dtype=float32)


In [296]:
import tensorflow as tf

In [297]:
# 8. Shuffle X theo chiều thứ nhất
X = tf.constant([[1, 2], [3, 4], [5, 6]])
# tf.random.shuffle sẽ xáo trộn các hàng
shuffled_X = tf.random.shuffle(X)
print("8. X sau khi shuffle hàng:\n", shuffled_X)

8. X sau khi shuffle hàng:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [298]:
# 9. Tạo tensor (10, 10, 3) và cắt thành (5, 5, 3)
# Giả lập một ảnh 10x10
original_tensor = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=255, dtype=tf.int32)
cropped_tensor = tf.image.random_crop(original_tensor, size=[5, 5, 3])
print("\n9. Kích thước sau khi crop:", cropped_tensor.shape)


9. Kích thước sau khi crop: (5, 5, 3)


In [299]:
# 10. Logic điều kiện trên hai tensor x, y
x = tf.random.uniform(shape=[5], minval=0, maxval=10)
y = tf.random.uniform(shape=[5], minval=0, maxval=10)
result_10 = tf.where(x < y, x + y, x - y)
print("\n10. Tensor x:", x.numpy())
print("    Tensor y:", y.numpy())
print("    Kết quả (x+y nếu x<y, ngược lại x-y):\n", result_10.numpy())


10. Tensor x: [0.45138597 8.789974   4.822592   0.359931   9.628552  ]
    Tensor y: [1.7582631  0.45295954 5.788152   3.9749646  3.901732  ]
    Kết quả (x+y nếu x<y, ngược lại x-y):
 [ 2.209649   8.337015  10.610744   4.3348956  5.7268205]


In [300]:
# 11. Phép toán ma trận và đường chéo
x_11 = tf.random.uniform(shape=(3, 2), minval=5, maxval=10)
y_11 = tf.random.uniform(shape=(2, 3), minval=15, maxval=20)

# x + y chỉ thực hiện được khi cùng kích thước.
# x (3,2) và y (2,3) khác kích thước
# Chuyển vị
y_transposed = tf.transpose(y_11)
sum_result = x_11 + y_transposed

# Lấy đường chéo của x
diag_x = tf.linalg.diag_part(x_11)

print("\n11. Đường chéo của x:", diag_x.numpy())
print("    Kết quả x + y_T:\n", sum_result.numpy())


11. Đường chéo của x: [9.387012 8.124609]
    Kết quả x + y_T:
 [[24.816948 24.900686]
 [25.891647 24.076038]
 [28.192787 26.200602]]


In [301]:
# 12. Tạo 2 tensor ngẫu nhiên và hàm tính toán (chuyển vào graph với @tf.function)
@tf.function
def compute_ops(x, y):
    return x + y, x - y, x * y, x / y

x12 = tf.random.normal((3, 2, 2))
y12 = tf.random.normal((3, 2, 2))
add, sub, mul, div = compute_ops(x12, y12)
print("12. Kết quả tính toán graph:\n Cộng:\n", add.numpy())

12. Kết quả tính toán graph:
 Cộng:
 [[[ 0.6721318   1.1654747 ]
  [-0.22623186  0.7577485 ]]

 [[ 0.94517756  2.7058728 ]
  [-0.05717021  0.99481666]]

 [[-0.53489274  1.4702396 ]
  [-1.9737854  -3.483666  ]]]


In [302]:
# 13. Model tính tổng hai tensor
class SumModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x + y

sum_model = SumModel()
print("\n13. Kết quả SumModel:\n", sum_model(x12, y12).numpy())


13. Kết quả SumModel:
 [[[ 0.6721318   1.1654747 ]
  [-0.22623186  0.7577485 ]]

 [[ 0.94517756  2.7058728 ]
  [-0.05717021  0.99481666]]

 [[-0.53489274  1.4702396 ]
  [-1.9737854  -3.483666  ]]]


In [303]:
# 14. Model tính hiệu và tích
class DiffProdModel(tf.Module):
    @tf.function
    def compute(self, x, y):
        return x - y, x * y

diff_prod_model = DiffProdModel()
diff, prod = diff_prod_model.compute(x12, y12)
print("\n14. Kết quả DiffProdModel (Hiệu):\n", diff.numpy())


14. Kết quả DiffProdModel (Hiệu):
 [[[-0.38228965  2.0113344 ]
  [ 0.11943479 -2.7744608 ]]

 [[-0.7620846   0.96933556]
  [ 0.9287727  -0.30421603]]

 [[ 1.3729072   0.7088294 ]
  [ 0.89311606 -1.9326434 ]]]


In [304]:
# 15. Model tính chu vi hình chữ nhật P = (a + b) * 2
class PerimeterModel(tf.Module):
    @tf.function
    def calculate(self, a, b):
        return (a + b) * 2

peri_model = PerimeterModel()
print("\n15. Chu vi hcn (a=3, b=4):", peri_model.calculate(3.0, 4.0).numpy())


15. Chu vi hcn (a=3, b=4): 14.0


In [305]:
# 16. Model tính diện tích toàn phần hình hộp chữ nhật
class SurfaceAreaModel(tf.Module):
    @tf.function
    def calculate(self, a, b, c):
        s_xung_quanh = (a + b) * c * 2
        s_toan_phan = (a * b) * 2 + s_xung_quanh
        return s_toan_phan

sa_model = SurfaceAreaModel()
print("\n16. Diện tích toàn phần (a=2, b=3, c=4):", sa_model.calculate(2.0, 3.0, 4.0).numpy())


16. Diện tích toàn phần (a=2, b=3, c=4): 52.0


In [306]:
# 12. Tạo 2 tensor (3,2,2), tính toán cộng, trừ, nhân, chia
@tf.function
def compute_arithmetic(x, y):
    return x + y, x - y, x * y, x / y

x12 = tf.random.normal((3, 2, 2))
y12 = tf.random.normal((3, 2, 2))
add, sub, mul, div = compute_arithmetic(x12, y12)

print("--- BÀI 12: Phép toán trên Tensor ---")
print("Cộng:\n", add.numpy())

--- BÀI 12: Phép toán trên Tensor ---
Cộng:
 [[[-0.2701011   0.28252834]
  [-0.31637272  1.7511954 ]]

 [[ 1.1304597   0.31318298]
  [ 0.69172996  2.123586  ]]

 [[ 0.3336984  -1.327123  ]
  [ 1.3620355   2.446258  ]]]


In [307]:
# Bài 17: Chứng minh AD // BC (Trường hợp True)
import tensorflow as tf

class ProveParallelModel(tf.Module):
    @tf.function
    def _is_equal_length(self, u, v):
        len_u_sq = tf.reduce_sum(tf.square(u))
        len_v_sq = tf.reduce_sum(tf.square(v))
        return tf.abs(len_u_sq - len_v_sq) < 1e-5

    @tf.function
    def prove_bai17(self, A, B, C, D):
        AB = B - A
        CD = D - C
        AD = D - A
        BC = C - B

        cond_AD_equal_BC = self._is_equal_length(AD, BC)
        cond_AB_equal_CD = self._is_equal_length(AB, CD)
        return cond_AD_equal_BC & cond_AB_equal_CD

# Tọa độ giả lập để kết quả ra True (Hình thang cân ABCD)
A = tf.constant([0.0, 2.0])
B = tf.constant([2.0, 2.0])
C = tf.constant([3.0, 0.0])
D = tf.constant([1.0, 0.0])

model_17 = ProveParallelModel()
print(f"Kết quả Bài 17 (AD // BC): {model_17.prove_bai17(A, B, C, D).numpy()}")

Kết quả Bài 17 (AD // BC): True


In [308]:
# Bài 19: Định lý đường trung bình (Sửa tọa độ để MN = MB ra True)
import tensorflow as tf

class ProveMidpointModel(tf.Module):
    @tf.function
    def _is_parallel(self, u, v):
        return tf.abs(u[0] * v[1] - u[1] * v[0]) < 1e-5

    @tf.function
    def _is_equal_length(self, u, v):
        return tf.abs(tf.reduce_sum(tf.square(u)) - tf.reduce_sum(tf.square(v))) < 1e-5

    @tf.function
    def prove_bai19(self, M, N, B, C):
        MN = N - M; BC = C - B; MB = B - M
        return self._is_equal_length(MN, MB) & self._is_parallel(MN, BC)

M = tf.constant([0.0, 2.0])
N = tf.constant([2.0, 1.0])
B = tf.constant([-1.0, 0.0])
C = tf.constant([3.0, -2.0])

model_19 = ProveMidpointModel()
print(f"Kết quả Bài 19 (NA = NC): {model_19.prove_bai19(M, N, B, C).numpy()}")

Kết quả Bài 19 (NA = NC): True
